name: Test and build the library

on: pull_request

jobs:
  test-and-build-the-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 'Setup Node'
        runs:
          using: 'composite'
          steps:
            - name: Read .nvmrc
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              shell: bash
              id: nvm

            - name: Use Node.js (.nvmrc)
              uses: actions/setup-node@v2
              with:
                node-version: '${{ steps.nvm.outputs.NVMRC }}'
                cache: 'yarn'

      - name: Install dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Create production build
        run: yarn build
